# Generated by Django 5.0.6 on 2024-06-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_alter_audiofile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
