# Generated by Django 5.0.6 on 2024-06-14 13:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_remove_audiofile_uploaded_at_alter_audiofile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
